// packages/db/src/rls.ts
//
// RLS helper per Roadmap v2.1 §4.3.5 and ADR-001.
//
// Exports tenantPolicy() — a factory that returns a Drizzle pgPolicy with
// the standard tenant isolation policy. Apply this policy to EVERY
// tenant-scoped table.
//
// The policy:
//   USING      (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
//   WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
//
// How it works:
// - current_setting('app.current_tenant', true) reads the session variable
//   set by the TenantInterceptor (Phase 5). The second arg (true) is
//   missing_ok — return NULL if the setting doesn't exist (instead of erroring).
// - NULLIF(..., '') converts empty string to NULL.
// - ::uuid casts the result to UUID.
// - If the setting is missing/empty, the result is NULL, and
//   tenant_id = NULL is false for all rows → NO rows visible.
//   This is the correct security posture: the app MUST set
//   app.current_tenant before querying tenant-scoped tables.
//
// FORCE ROW LEVEL SECURITY (ADR-001 point 2):
// Drizzle 0.40.1 does NOT have a forceRLS() API. ENABLE ROW LEVEL SECURITY
// is generated by drizzle-kit when enableRLS() is called on the table.
// FORCE is added via a post-migration SQL file (packages/db/sql/003_force_rls.sql)
// in PR C — see JC-18-3 in the PR B description. The PR E CI test verifies
// that FORCE is set on every tenant-scoped table.

import { sql } from 'drizzle-orm';
import { pgPolicy } from 'drizzle-orm/pg-core';

/**
 * Standard tenant isolation RLS policy.
 *
 * @param tableName - The name of the table this policy applies to. Used to
 *   generate a unique policy name for debugging (e.g., `app_user_tenant_isolation`).
 *   Postgres policy names are per-table, so the same name could be reused,
 *   but unique names make `pg_policies` queries easier to read.
 *
 * @returns A Drizzle PgPolicy to include in the table's extraConfig array.
 *
 * Usage:
 *   export const appUser = pgTable('app_user', {...}, (t) => [
 *     tenantPolicy('app_user'),
 *     index('app_user_tenant_idx').on(t.tenantId).where(t.deletedAt.isNull()),
 *   ]);
 *   appUser.enableRLS();
 */
export function tenantPolicy(tableName: string) {
  return pgPolicy(`${tableName}_tenant_isolation`, {
    as: 'permissive',
    for: 'all',
    to: 'public',
    using: sql`tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid`,
    withCheck: sql`tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid`,
  });
}
